//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a Chugin boilerplate, generated by chuginate!
//-----------------------------------------------------------------------------

// this should align with the correct versions of these ChucK files
#include "chuck_dl.h"
#include "chuck_def.h"

// python includes and defs
#define PY_SSIZE_T_CLEAN
#include <Python.h>

// general includes
#include <stdio.h>
#include <limits.h>

// declaration of chugin constructor
CK_DLL_CTOR(hydra_ctor);
// declaration of chugin desctructor
CK_DLL_DTOR(hydra_dtor);

// example of getter/setter
CK_DLL_MFUN(hydra_setParam);
CK_DLL_MFUN(hydra_getParam);

// for Chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK(hydra_tick);

// this is a special offset reserved for Chugin internal data
t_CKINT hydra_data_offset = 0;


// class definition for internal Chugin data
// (note: this isn't strictly necessary, but serves as example
// of one recommended approach)
class Hydra
{
public:
    // constructor
    Hydra( t_CKFLOAT fs)
    {
        m_param = 0;
    }

    // for Chugins extending UGen
    SAMPLE tick( SAMPLE in )
    {
        // default: this passes whatever input is patched into Chugin
        return in;
    }

    // set parameter example
    t_CKFLOAT setParam( t_CKFLOAT p )
    {
        m_param = p;
        return p;
    }

    // get parameter example
    t_CKFLOAT getParam() { return m_param; }
    
private:
    // instance data
    t_CKFLOAT m_param;
};


// query function: chuck calls this when loading the Chugin
// NOTE: developer will need to modify this function to
// add additional functions to this Chugin
CK_DLL_QUERY( Hydra )
{
    // hmm, don't change this...
    QUERY->setname(QUERY, "Hydra");
    
    // begin the class definition
    // can change the second argument to extend a different ChucK class
    QUERY->begin_class(QUERY, "Hydra", "UGen");

    // register the constructor (probably no need to change)
    QUERY->add_ctor(QUERY, hydra_ctor);
    // register the destructor (probably no need to change)
    QUERY->add_dtor(QUERY, hydra_dtor);
    
    // for UGen's only: add tick function
    QUERY->add_ugen_func(QUERY, hydra_tick, NULL, 1, 1);
    
    // NOTE: if this is to be a UGen with more than 1 channel, 
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    // example of adding setter method
    QUERY->add_mfun(QUERY, hydra_setParam, "float", "param");
    // example of adding argument to the above method
    QUERY->add_arg(QUERY, "float", "arg");

    // example of adding getter method
    QUERY->add_mfun(QUERY, hydra_getParam, "float", "param");
    
    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    hydra_data_offset = QUERY->add_mvar(QUERY, "int", "@h_data", false);

    // end the class definition
    // IMPORTANT: this MUST be called!
    QUERY->end_class(QUERY);

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the constructor
CK_DLL_CTOR(hydra_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, hydra_data_offset) = 0;
    
    // instantiate our internal c++ class representation
    Hydra * h_obj = new Hydra(API->vm->get_srate(API, SHRED));
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, hydra_data_offset) = (t_CKINT) h_obj;
}


// implementation for the destructor
CK_DLL_DTOR(hydra_dtor)
{
    // get our c++ class pointer
    Hydra * h_obj = (Hydra *) OBJ_MEMBER_INT(SELF, hydra_data_offset);
    // check it
    if( h_obj )
    {
        // clean up
        delete h_obj;
        OBJ_MEMBER_INT(SELF, hydra_data_offset) = 0;
        h_obj = NULL;
    }
}


// implementation for tick function
CK_DLL_TICK(hydra_tick)
{
    // get our c++ class pointer
    Hydra * h_obj = (Hydra *) OBJ_MEMBER_INT(SELF, hydra_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if(h_obj) *out = h_obj->tick(in);

    // yes
    return TRUE;
}


// example implementation for setter
CK_DLL_MFUN(hydra_setParam)
{
    // get our c++ class pointer
    Hydra * h_obj = (Hydra *) OBJ_MEMBER_INT(SELF, hydra_data_offset);
    // set the return value
    RETURN->v_float = h_obj->setParam(GET_NEXT_FLOAT(ARGS));
}


// example implementation for getter
CK_DLL_MFUN(hydra_getParam)
{
    // get our c++ class pointer
    Hydra * h_obj = (Hydra *) OBJ_MEMBER_INT(SELF, hydra_data_offset);
    // set the return value
    RETURN->v_float = h_obj->getParam();
}
